---
title: "Example without technical replicates"
author: "Jordi Camps"
date: "October 31, 2017"
output: html_document
---


# Load librararies
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qpcrviia7)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
```

# Import and prepare data
```{r}
#Import data
qpcr <- read_qpcr("Data/2017-09-20 124839 FAP-C2C12-Muscle qPCR validation MC.xls", sheet = 3)
#Import annotation
ann_samples <- read_annotation("Data/Annotations_124839_samples.xlsx")
ann_genes <- read_annotation("Data/Annotations_124839_primers.xlsx")


#Merge and tidy
join_and_clean_qpcr(qpcr)
```

## Quality control
### Primers and samples
```{r}
par(mfrow=c(1,1))
hist(qpcr$CT, main = "CT values")

#Plot CT values for samples
ggplot(qpcr, aes(Sample, CT)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("CT values per sample")

#Plot CT values for primers
ggplot(qpcr, aes(Gene, CT)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("CT values per primer")
```

#### Remove blanc
```{r}
qpcr <- remove_blanc(qpcr)
hist(qpcr$CT, main = "CT after removal blanc")
```

#### Split hkg from endogenous
```{r}
split_genes(qpcr)
```


### Endogenous genes
```{r}
#Set min and max ct value
endog <- set_min_max_CT(endog, 10, 40)
hist(endog$CT, main = "CT after set baseline")

#Double meltcurve peaks
list_double_meltcurves(endog, CT = "CT")
remove_bad_meltcurves()
```

### Housekeeping genes
```{r}
#QC on housekeeping genes
qc_hkg(hkg)
```

#### Remove Rpl13a
```{r}
remove_primer(endog, "Rpl13a")
```


#### Take geometric average all housekeeping genes
```{r}
mean_hkg <- calculate_mean_hkg(hkg)
qc_mean_hkg(mean_hkg)
```

#### Remove outliers
```{r}
mean_hkg$CT_avg_hkg <- remove_outliers(mean_hkg$CT_avg_hkg)
```


## Delta CT
### Calculate Delta CT
```{r}
calculate_DCT(endog, mean_hkg, cols = c("Cell_type", "Condition", "Mouse"))
```

### Plot Delta CT
#### Scatter plot
```{r}
plot_scatter(endog, x.var = "Cell_type", y.var = "DCt", col.var = "Condition")
plot_scatter_per_gene(endog, "Dcn", x.var = "Cell_type", y.var = "DCt", col.var = "Condition", theme = 18) +
  labs(y = "Delta CT") +
  scale_fill_discrete(name = "Cell type") +
  scale_x_discrete(labels = c("C2C12 GFP" = "C2C12", "FAP" = "FAP", "TA" = "Tibialis\nanterior"))
```


### Plot relative expression
#### Plot scatter
```{r}
plot_scatter(endog, x.var = "Cell_type", y.var = "rel_expr", col.var = "Condition") 
plot_scatter_per_gene(endog, "Dcn", x.var = "Cell_type", y.var = "rel_expr", col.var = "Condition", theme = 18) +
  labs(y = "Relative expression") +
  scale_fill_discrete(name = "Cell type") +
  scale_x_discrete(labels = c("C2C12 GFP" = "C2C12", "FAP" = "FAP", "TA" = "Tibialis\nanterior"))
```
