---
title: "qPCR validations single-cell 1moWTB"
author: "Jordi Camps"
date: "3 oktober 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qpcrviia7)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
```

## Import and prepare data
```{r}
#Import data
qpcr <- read_qpcr("Data/2017-09-18 Smartseq2 Hanne.xlsx")
#Import annotation
ann_samples <- read_annotation("Data/Annotations_samples.xlsx")
ann_genes <- read_annotation("Data/Annotations_primers.xlsx")


#Merge and tidy
join_and_clean_qpcr(qpcr)
```

## Quality control
### Primers and samples
```{r}
par(mfrow=c(1,1))
hist(qpcr$CT, main = "CT values")

#Plot CT values for samples
ggplot(qpcr, aes(Sample, CT)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("CT values per sample")

#Plot CT values for primers
ggplot(qpcr, aes(Primer, CT)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("CT values per primer")

#Filter sample
filter_sample(qpcr, "Sample 11")
filter_sample(qpcr, "Sample 1")
filter_sample(qpcr, "Sample 4")
filter_sample(qpcr, "Sample 16")
```

### Remove blanc and split endogenous and housekeeping genes
```{r}
#Remove blanc
remove_sample(qpcr, "Sample 16")
hist(qpcr$CT, main = "CT after removal blanc")

#Split hkg from endogenous
split_genes(qpcr)
```

### Endogenous genes
```{r}
#Set min and max ct value
set_min_max_CT_endog(9, 40)
hist(endog$CT, main = "CT after set baseline")

#Double meltcurve peaks
list_double_meltcurves(endog)
remove_bad_meltcurves()
```

### Housekeeping genes
```{r}
#QC on housekeeping genes
qc_hkg(hkg)

#Remove Rab35
hkg <- remove_primer(hkg, "Rab35")

#Remove CT values above or below a specific threshold
hkg <- hkg %>%
  spread(Primer, CT) %>%
  mutate(Rpl13a = replace(Rpl13a, Rpl13a > 30, NA)) %>%
  gather(Primer, CT, -Sample)
qc_hkg(hkg)

hkg <- hkg %>%
  spread(Primer, CT) %>%
  mutate(Psma3 = replace(Psma3, Psma3 > 15, NA)) %>%
  gather(Primer, CT, -Sample)
qc_hkg(hkg)

#Take geometric average all housekeeping genes
mean_hkg <- calculate_mean_hkg(hkg)
qc_mean_hkg(hkg)
mean_hkg$CT_avg_hkg <- remove_outliers(mean_hkg$CT_avg_hkg)
```

## Calculate Delta CT
```{r}
calculate_DCT(endog, mean_hkg, cols = c("Cell_type", "Condition", "Mouse"))
```

## Plot Delta CT
```{r}
theme_set(theme_few())
plot_scatter(endog, x.var = "Cell_type", y.var = "DCt", col.var = "Condition") +
  labs(title = "Scatterplot all genes", y = "Delta CT", x = "Cell type")
plot_scatter_per_gene(endog, "Dcn", x.var = "Cell_type", y.var = "DCt", col.var = "Condition") +
  labs(title = "Scatterplot Decorin", y = "Delta CT", x = "Cell type")
plot_bar(endog, x.var = "Cell_type", y.var = "DCt", fill.var = "Condition") +
  labs(title = "Barplot all genes", y = "Delta CT", x = "Cell type")
plot_bar_per_gene(endog, "Dcn", "Cell_type", y.var = "DCt", fill.var = "Condition") +
  labs(title = "Barplot Decorin", y = "Delta CT", x = "Cell type")
plot_pointrange(endog, x.var = "Cell_type", y.var = "DCt", col.var = "Condition") +
  labs(title = "Pointrange all genes", y = "Delta CT", x = "Cell type")
plot_pointrange_per_gene(endog, "Dcn", x.var = "Cell_type", y.var = "DCt", col.var = "Condition") +
  labs(title = "Pointrange Decorin", y = "Delta CT", x = "Cell type")
```

## Plot relative expression
```{r}
plot_scatter(endog, x.var = "Cell_type", y.var = "rel_expr", col.var = "Condition") +
  labs(title = "Scatterplot all genes", y = "Relative expression", x = "Cell type")
plot_pointrange(endog, x.var = "Cell_type", y.var = "rel_expr", col.var = "Condition") +
  labs(title = "Pointrange all genes", y = "Relative expression", x = "Cell type")
plot_bar_per_gene(endog, "Dcn", x.var = "Cell_type", y.var = "rel_expr", col.var = "Condition") +
  labs(title = "Decorin", y = "Relative expression", x = "Cell type")
```

